// Generated by CoffeeScript 1.10.0
var cron;

cron = require('cron').CronJob;

module.exports = function(robot) {
  return new cron('0 50 19 * * 1-7', (function(_this) {
    return function() {
      return robot.send({
        room: "#baigie-bottest"
      }, "時間ですね");
    };
  })(this), null, true, "Asia/Tokyo");
};
